"""Additional fields in Task

Revision ID: 00180029bdc2
Revises: 7671222ca848
Create Date: 2024-11-16 21:47:21.100312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00180029bdc2'
down_revision: Union[str, None] = '7671222ca848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'active')
    # ### end Alembic commands ###
